name: cache reuse

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore:
      - "scripts/*"
      - "*.md"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "scripts/*"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  cache-pixi:
    uses: Glatzel/template/.github/workflows/cache-pixi.yml@main
    with: 
      machine: windows-latest

  pytest:
    uses: Glatzel/template/.github/workflows/pytest.yml@main
    with:
      name: test
      machine: windows-latest
      test_path: ./src
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}