name: test
on:
    workflow_dispatch:
env:
    TAG: ""
jobs:
  example:
    runs-on: windows-latest
    steps:
      - run: echo "TAG=123.45.6" >> "$env:GITHUB_ENV"
      - run: Write-Output "$env:TAG"

  example1:
    needs: example
    runs-on: windows-latest
    steps:
      - run: Write-Output "$env:TAG"
