name: CI

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore:
      - "scripts/*"
      - "*.md"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "scripts/*"
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  cache:
    if: ${{github.event_name== 'workflow_dispatch'}}
    uses: Glatzel/template/.github/workflows/cache-pixi.yml@main
    with:
      machine: windows-latest
      envs: >-
        default
        a
  restore-cache:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        with:
          path: '~\AppData\Local\rattler'
          key: pixi-win-64-
          restore-keys: pixi-${{ runner.os }}-