name: test

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  cache:
    strategy:
      matrix:
        version: [1, 2, 3]
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v4
